/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Shortlist } from "./Shortlist";
import { ShortlistCountArgs } from "./ShortlistCountArgs";
import { ShortlistFindManyArgs } from "./ShortlistFindManyArgs";
import { ShortlistFindUniqueArgs } from "./ShortlistFindUniqueArgs";
import { DeleteShortlistArgs } from "./DeleteShortlistArgs";
import { ShortlistService } from "../shortlist.service";
@graphql.Resolver(() => Shortlist)
export class ShortlistResolverBase {
  constructor(protected readonly service: ShortlistService) {}

  async _shortlistsMeta(
    @graphql.Args() args: ShortlistCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Shortlist])
  async shortlists(
    @graphql.Args() args: ShortlistFindManyArgs
  ): Promise<Shortlist[]> {
    return this.service.shortlists(args);
  }

  @graphql.Query(() => Shortlist, { nullable: true })
  async shortlist(
    @graphql.Args() args: ShortlistFindUniqueArgs
  ): Promise<Shortlist | null> {
    const result = await this.service.shortlist(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shortlist)
  async deleteShortlist(
    @graphql.Args() args: DeleteShortlistArgs
  ): Promise<Shortlist | null> {
    try {
      return await this.service.deleteShortlist(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
