/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Placement } from "./Placement";
import { PlacementCountArgs } from "./PlacementCountArgs";
import { PlacementFindManyArgs } from "./PlacementFindManyArgs";
import { PlacementFindUniqueArgs } from "./PlacementFindUniqueArgs";
import { DeletePlacementArgs } from "./DeletePlacementArgs";
import { PlacementService } from "../placement.service";
@graphql.Resolver(() => Placement)
export class PlacementResolverBase {
  constructor(protected readonly service: PlacementService) {}

  async _placementsMeta(
    @graphql.Args() args: PlacementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Placement])
  async placements(
    @graphql.Args() args: PlacementFindManyArgs
  ): Promise<Placement[]> {
    return this.service.placements(args);
  }

  @graphql.Query(() => Placement, { nullable: true })
  async placement(
    @graphql.Args() args: PlacementFindUniqueArgs
  ): Promise<Placement | null> {
    const result = await this.service.placement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Placement)
  async deletePlacement(
    @graphql.Args() args: DeletePlacementArgs
  ): Promise<Placement | null> {
    try {
      return await this.service.deletePlacement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
